<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0JP1GH8" ignored="8" name="Default test" tests="1" failures="1" timestamp="2020-10-30T08:22:25 ICT" time="10.023" errors="0">
  <testcase name="test1" time="9.911" classname="com.AssKiemThuNC.TestGarenaDK">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.AssKiemThuNC.TestGarenaDK.test1(TestGarenaDK.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test6" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test6 -->
  <testcase name="test5" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test5 -->
  <testcase name="test4" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test3" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="test9" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test9 -->
  <testcase name="test8" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test8 -->
  <testcase name="test10" time="0.0" classname="com.AssKiemThuNC.TestGarenaDK">
    <ignored/>
  </testcase> <!-- test10 -->
</testsuite> <!-- Default test -->
